#!/bin/bash

SEC_FILE=./SECURITY.md
CON_FILE=./CONTRIBUTING.md
COC_FILE=./CODE_OF_CONDUCT.md

PR_FILE=./.github/PULL_REQUEST_TEMPLATE.md

IT_FOLDER=./.github/ISSUE_TEMPLATE


rm -rf $SEC_FILE $COC_FILE $CON_FILE $PR_FILE $IT_FOLDER